"""
Real (no-mock) tests for build.py task commands.

Uses actual git dirty state and the --dry-run flag via subprocess.
Requires fhir-omop-ig and matchbox repos cloned alongside matchbox_scripts.
Does not require a running stack, Docker, or network access.

Note: matchbox_scripts itself has pre-existing uncommitted changes
(load_duckdb.py, transforms.py, etl_report_*.html), so dev-overlay will
always be True in tests that call 'run local'. Tests are written to
reflect this real state rather than fighting it.
"""
import subprocess
import sys
import pytest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import build
from build import _detect_dirty, IG_DIR, SCRIPTS_DIR, REPO_ROOT, DQD_DIR

MATCHBOX_DIR = REPO_ROOT / 'matchbox'
BUILD_PY = SCRIPTS_DIR / 'build.py'

# Skip the whole module if the repos aren't cloned.
pytestmark = pytest.mark.skipif(
    not IG_DIR.exists() or not MATCHBOX_DIR.exists(),
    reason='fhir-omop-ig and matchbox repos must be cloned alongside matchbox_scripts',
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run_dry(*args):
    """Call build.py with --dry-run and return parsed output dict."""
    result = subprocess.run(
        [sys.executable, str(BUILD_PY), *args, '--dry-run'],
        capture_output=True, text=True, cwd=str(SCRIPTS_DIR),
    )
    parsed = {}
    for line in result.stdout.splitlines():
        if line.startswith('steps: '):
            parsed['steps'] = line[len('steps: '):].split()
        elif line.startswith('ig-source: '):
            parsed['ig_source'] = line[len('ig-source: '):]
        elif line.startswith('dev-overlay: '):
            parsed['dev_overlay'] = line[len('dev-overlay: '):] == 'True'
    return parsed


def _git_restore(path, cwd):
    subprocess.run(['git', 'restore', str(path)], cwd=str(cwd), check=True)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture()
def dirty_ig():
    """Write to the fhir-omop-ig sentinel file; restore on teardown."""
    path = IG_DIR / '.test-sentinel'
    path.write_text(path.read_text() + 'x')
    yield path
    _git_restore(path, IG_DIR)


@pytest.fixture()
def dirty_matchbox():
    """Write to the matchbox sentinel file; restore on teardown."""
    path = MATCHBOX_DIR / '.test-sentinel'
    path.write_text(path.read_text() + 'x')
    yield path
    _git_restore(path, MATCHBOX_DIR)


# ---------------------------------------------------------------------------
# TestDetectDirty — exercises _detect_dirty against real git repos
# ---------------------------------------------------------------------------

class TestDetectDirty:
    def test_WHEN_fhir_omop_ig_has_only_autogenerated_xml_dirty_SHOULD_return_false_with_exclude(self):
        # FHIR-omop.xml is always modified (auto-generated); _resolve_run excludes it
        assert _detect_dirty(IG_DIR, exclude=['FHIR-omop.xml']) is False

    def test_WHEN_fhir_omop_ig_fml_file_modified_SHOULD_return_true_with_exclude(self, dirty_ig):
        assert _detect_dirty(IG_DIR, exclude=['FHIR-omop.xml']) is True

    def test_WHEN_fhir_omop_ig_fml_restored_SHOULD_return_false_again_with_exclude(self, dirty_ig):
        assert _detect_dirty(IG_DIR, exclude=['FHIR-omop.xml']) is True
        _git_restore(dirty_ig, IG_DIR)
        assert _detect_dirty(IG_DIR, exclude=['FHIR-omop.xml']) is False

    def test_WHEN_matchbox_clean_SHOULD_return_false(self):
        assert _detect_dirty(MATCHBOX_DIR) is False

    def test_WHEN_matchbox_file_modified_SHOULD_return_true(self, dirty_matchbox):
        assert _detect_dirty(MATCHBOX_DIR) is True

    def test_WHEN_matchbox_scripts_has_preexisting_changes_SHOULD_return_true(self):
        # matchbox_scripts has real uncommitted changes (load_duckdb.py etc.)
        assert _detect_dirty(SCRIPTS_DIR) is True


# ---------------------------------------------------------------------------
# TestDryRunRealGitState — full subprocess calls, real git state
# ---------------------------------------------------------------------------

class TestDryRunRealGitState:
    def test_WHEN_run_upstream_SHOULD_always_plan_ig_docker_restart_etl(self):
        out = _run_dry('run', 'upstream')
        assert out['steps'] == ['ig', 'docker', 'restart', 'etl']
        assert out['ig_source'] == 'upstream'
        assert out['dev_overlay'] is False

    def test_WHEN_run_branch_SHOULD_plan_ig_docker_restart_etl_with_branch_source(self):
        out = _run_dry('run', 'my-branch')
        assert out['steps'] == ['ig', 'docker', 'restart', 'etl']
        assert out['ig_source'] == 'my-branch'
        assert out['dev_overlay'] is False

    def test_WHEN_run_local_scripts_already_dirty_SHOULD_set_dev_overlay(self):
        # matchbox_scripts is dirty in the current working state
        out = _run_dry('run', 'local')
        assert out['dev_overlay'] is True
        assert 'restart' in out['steps']
        assert 'etl' in out['steps']

    def test_WHEN_run_local_ig_dirty_SHOULD_plan_ig_docker_and_set_local_source(self, dirty_ig):
        out = _run_dry('run', 'local')
        assert 'ig' in out['steps']
        assert 'docker' in out['steps']
        assert out['ig_source'] == 'local'
        assert out['dev_overlay'] is True  # matchbox_scripts still dirty

    def test_WHEN_run_local_ig_only_autogenerated_xml_dirty_SHOULD_not_plan_ig_step(self):
        # FHIR-omop.xml is excluded; no real IG change → ig step should not appear
        out = _run_dry('run', 'local')
        assert 'ig' not in out['steps']
        assert out['ig_source'] == 'upstream'

    def test_WHEN_run_local_matchbox_dirty_SHOULD_plan_mvn_docker(self, dirty_matchbox):
        out = _run_dry('run', 'local')
        assert 'mvn' in out['steps']
        assert 'docker' in out['steps']

    def test_WHEN_run_local_matchbox_clean_SHOULD_not_plan_mvn_step(self):
        out = _run_dry('run', 'local')
        assert 'mvn' not in out['steps']

    def test_WHEN_test_local_ig_dirty_SHOULD_append_test_step(self, dirty_ig):
        out = _run_dry('test', 'local')
        assert 'ig' in out['steps']
        assert out['steps'][-1] == 'test'

    def test_WHEN_run_alone_SHOULD_plan_restart_and_etl_only(self):
        out = _run_dry('run')
        assert out['steps'] == ['restart', 'etl']

    def test_WHEN_test_alone_SHOULD_plan_restart_etl_test(self):
        out = _run_dry('test')
        assert out['steps'] == ['restart', 'etl', 'test']
